[web]
app-server ansible_host=localhost ansible_connection=local

[web:vars]
ansible_python_interpreter=/usr/bin/python3
app_user=appuser
app_group=appuser
app_dir=/opt/infrastructure-automation
log_dir=/var/log/infrastructure-automation
